import { getCurrentWeather, checkWeatherAlert, isWeatherConfigured } from './weatherService.js';
import Alert from '../models/Alert.js';
import InstructorNotification from '../models/InstructorNotification.js';
import Instructor from '../models/Instructor.js';

/**
 * Weather Scheduler Service
 * Automatically checks weather for Malaybalay City, Bukidnon and creates alerts if needed
 */

let schedulerInterval = null;
let io = null;

// Configuration
const WEATHER_CITY = 'Malaybalay';
const WEATHER_COUNTRY_CODE = 'PH';
const CHECK_INTERVAL_MINUTES = 60; // Check every 60 minutes (1 hour)
const ALERT_SEVERITY_THRESHOLD = 'warning'; // Only create alerts for 'warning' or 'danger'

/**
 * Check weather and create alerts if severe conditions detected
 */
const checkWeatherAndAlert = async () => {
  try {
    if (!isWeatherConfigured()) {
      console.log('⚠️ Weather scheduler: OpenWeatherMap API not configured');
      return;
    }

    console.log(`🌤️ Checking weather for ${WEATHER_CITY}, ${WEATHER_COUNTRY_CODE}...`);
    
    // Get current weather
    const result = await getCurrentWeather(WEATHER_CITY, WEATHER_COUNTRY_CODE);
    const alertCheck = checkWeatherAlert(result.data);

    console.log(`📊 Weather: ${result.data.temperature}°C, ${result.data.description}`);
    console.log(`⚠️ Alert Status: ${alertCheck.hasAlert ? alertCheck.severity : 'None'}`);

    // Only create alerts if severity is warning or danger
    if (alertCheck.hasAlert && 
        (alertCheck.severity === 'warning' || alertCheck.severity === 'danger')) {
      
      // Check if similar alert already exists (avoid duplicates)
      const recentAlert = await Alert.findOne({
        type: 'weather-alert',
        createdAt: { $gte: new Date(Date.now() - 60 * 60 * 1000) } // Last hour
      });

      if (recentAlert) {
        console.log('ℹ️ Similar weather alert already exists, skipping...');
        return;
      }

      // Create alert message
      const alertMessage = `⚠️ Weather Alert for ${WEATHER_CITY}: ${alertCheck.message} | Current: ${result.data.description}, ${result.data.temperature}°C`;
      
      // Create system alert
      const alert = await Alert.create({
        type: 'weather-alert',
        message: alertMessage,
        meta: {
          severity: alertCheck.severity,
          weatherData: result.data,
          alerts: alertCheck.alerts,
          city: WEATHER_CITY,
          countryCode: WEATHER_COUNTRY_CODE,
          autoGenerated: true
        }
      });

      console.log(`✅ Weather alert created: ${alert._id}`);

      // Notify all active instructors
      const instructors = await Instructor.find({ status: 'active' });
      const notifications = instructors.map(instructor => ({
        instructorEmail: instructor.email,
        title: 'Weather Alert',
        message: alertMessage,
        type: 'weather',
        read: false
      }));

      if (notifications.length > 0) {
        await InstructorNotification.insertMany(notifications);
        console.log(`📧 Notifications sent to ${notifications.length} instructors`);
      }

      // Emit socket event for real-time updates
      if (io) {
        io.emit('weather-alert', {
          alert,
          weather: result.data,
          alertCheck
        });
        console.log('📡 Real-time weather alert broadcasted');
      }
    } else {
      console.log('✅ No severe weather conditions detected');
    }
  } catch (error) {
    console.error('❌ Error in weather scheduler:', error.message);
  }
};

/**
 * Start the weather scheduler
 * @param {Object} socketIO - Socket.IO instance for real-time updates
 */
export const startWeatherScheduler = (socketIO = null) => {
  if (schedulerInterval) {
    console.log('⚠️ Weather scheduler already running');
    return;
  }

  if (!isWeatherConfigured()) {
    console.log('⚠️ Weather scheduler: OpenWeatherMap API not configured, scheduler not started');
    return;
  }

  io = socketIO;

  console.log(`🌤️ Starting weather scheduler for ${WEATHER_CITY}, ${WEATHER_COUNTRY_CODE}`);
  console.log(`⏰ Check interval: Every ${CHECK_INTERVAL_MINUTES} minutes`);

  // Run immediately on start
  checkWeatherAndAlert();

  // Then run on schedule
  schedulerInterval = setInterval(() => {
    checkWeatherAndAlert();
  }, CHECK_INTERVAL_MINUTES * 60 * 1000);

  console.log('✅ Weather scheduler started');
};

/**
 * Stop the weather scheduler
 */
export const stopWeatherScheduler = () => {
  if (schedulerInterval) {
    clearInterval(schedulerInterval);
    schedulerInterval = null;
    console.log('🛑 Weather scheduler stopped');
  }
};

/**
 * Get scheduler status
 */
export const getSchedulerStatus = () => {
  return {
    running: schedulerInterval !== null,
    city: WEATHER_CITY,
    countryCode: WEATHER_COUNTRY_CODE,
    intervalMinutes: CHECK_INTERVAL_MINUTES,
    configured: isWeatherConfigured()
  };
};

/**
 * Manually trigger weather check (for testing or manual checks)
 */
export const triggerWeatherCheck = async () => {
  await checkWeatherAndAlert();
};

